### ISSUE TITLE
Upload

### ISSUE THREAD

**Issue by herflis** [SenseNet/sn-list-controls-react#4]

**Comment by herflis** [comment]
![image](https://user-images.githubusercontent.com/6968860/40426660-ee41517c-5e9b-11e8-9195-9455d8db3300.png)


**ToDo: check upload file vs folder in Google Drive**
Props:
 - ContentId
 - Should display a dropdown:
    - Upload file
    - Upload folder
 - Should open native browse popup
 - Should display info with the progress during upload that can be closed
![image](https://user-images.githubusercontent.com/6968860/40426623-d6be780e-5e9b-11e8-919f-79a7e2cdc4dc.png)

![image](https://user-images.githubusercontent.com/6968860/40426573-b9e9cfda-5e9b-11e8-9ffb-092516dfcea8.png)

**Comment by kultsar** [comment]
Upload msg
- [ ] This will upload all files from "[dir]". --> "This will upload all directory contents "[dir]"." 

File upload
- [ ] Uploading same file: seemingly nothing happens, user does not know if file is overwritten or not.
- [ ] Uploading same file with modified content: seemingly nothing happens, user does not know if file is overwritten or not.

Dir upload
- [ ] Uploading same directory with same contents, confirmation dialog pops up, but afterwards nothing happens, upload progress does not appear. We could display the upload progress with failed uploads, informing user that directory/files already exists, or we could ask user if they want to overwrite directory contents.
- [ ] Uploading same directory with same contents *plus a new file*, confirmation dialog pops up, upload progress *appears*, same contents with matching filenames get a green tickmark. We have, though, a new entry with a red exclamation mark, named "..", and not the new filename. Could not reproduce this later on with this or with different directories. When uploading the same directory again with another new file, nothing happens after confirmation dialogue. Adding again a new file to dir, upload behaves the same, nothing happens. Confirmation message always counts number of files correctly. 

Progress list/bar
- [ ] Would be nice to be able to reopen upload progress list after closing it.
- [ ] Upload list progress bar does not go till the end, a few pixels are missing

**Comment by gallayl** [comment]
**Upload msg** - It's a native chrome feature, the notification text cannot be customized. See [this](https://stackoverflow.com/questions/50225019/how-to-remove-warning-message-in-chrome-when-uploading-a-directory) SO thread for more info
**Re-uploading files** -  There was a bug that the input controls has been triggered the upload on the *change* event - fixed in [dev branch](https://github.com/SenseNet/sn-dms-demo/commit/84e6c11318692a19aa943d22d02a8891787078b9)
**Overwriting files** - Currently the [incremental naming](https://community.sensenet.com/docs/content-naming-provider/) feature is on by default in the DMS, so uploaded files won't be overwritten but uploaded with an auto-incremental postfix, however re-uploading the same directory structure may fail
**Upload progress** - there was a bug with progress calculation when the upload doesn't have info about the files / chunks. fixed in the [dev branch](https://github.com/SenseNet/sn-dms-demo/commit/323b2f5fd1fcc04dd1f1080d6f7d3494f36e84c2)

We should do additional research / ux / specification / improvements  with the following scenarios:
 - Incremental naming is turned off, overwrite can be an issue
 - Re-uploading the same directory structure again, upload can be an issue, directory structure should be merged
 - Reopening the upload bar
 - Ordering upload bar items
 - Remove completed / failed items from the list
 - Displaying a more meaningful error message on failed uploads

**Comment by kultsar** [comment]
Upload progress bar still seems problematic:
* Uploaded a directory with 2 files. One failed, progress bar did not go till the end
* Uploaded another dir with another 2 files. No failure, but progress bar did not go till the end in this case either

I think that it should go till the end in both cases, but if needed, this could be made subject of the ongoing UX research.

**Comment by kultsar** [comment]
Upload progress bar seems to work well. It does not reach the end as the upload for certain files seem to last forever. Error might be on backend.
